#the ones with trailing spaces are problematic - eliminates the space.
# added a space to the title.  can always strip the extra space later - prevents words
#   from running together (i.e. SR STAFF -> SENIORSTAFF)

abbr_replace <- list (" SENIOR " = c(" SR ", " SR\\.", "^SR\\.", "^SR "),
                      " JUNIOR " = c(" JR ", " JR\\.", "^JR\\.", "^JR "),
                      " BUSINESS " = c(" BUS ", " BUS. "),
                      " : " = c(":"),
                      " OFFICER " = c(" OFCR"," OCIFER"," OFICER"),
                      "SENIOR VICE PRESIDENT " = c("(?<!,.)SVP", "(?<!,.)S\\.V\\.","^SVP"),
                      "EXECUTIVE VICE PRESIDENT " = c("(?<!,.)EVP","^EVP"),
                      "ASSISTANT VICE PRESIDENT " = c("(?<!,.)AVP","^AVP"),
                      "VICE PRESIDENT " = c("(?<!A|E|S)VP", "(?<!A|E|S|\\.)V\\.P","VICE-PRESIDENT"),
                      "EXECUTIVE " = c("EXEC\\.", "EXEC "),
                      "ASSOCIATE " = c("ASSOC\\.", "ASSOC ", "ASSO\\.", "AFFILIATE(?= |$)"),
                      "DIRECTOR " = c("DIR\\.", "DIR "), 
                      "MANAGER " = c("MGR\\.", "MGR "),
                      "ASSISTANT " = c("ASST", "ASST\\."),
                      "PRESIDENT " = c("PRES ", "PRES\\."),
                      "PROFESSOR " = c("PROF(?= |\\.|$|/)","FACULTY","PROF.+SOR"),
                      "WRITER " = c("AUTHOR(?= |$|!|,|/)","COLUMNIST"),
                      "CLERGY " = c("PASTOR(?= |$|,|/)","PRIEST","CHAPLAIN","BISHOP"),
                      "TEACHER " = c("EDUCATOR"),
                      "CONSULTANT " = c("CONSULTING"),
                      "SCIENTIST " = c("PHYSICIST","CHEMIST","BIOLIGIST","MATHEMATICIAN",
                                       "STATISTICIAN","EPIDEMIOLOGIST"),
                      "ATTORNEY " = c("COUNSEL(?=$| |LOR|/)"),
                      "ARTIST " = c("PIANIST","MUSICIAN","PAINTER","SCULPTOR","PHOTOGRAPHER",
                                    "VIDEOGRAPHER","DRUMMER","PERCUSSIONIST"),
                      "APPRAISER " = c("APPRAIS(?=ER|AL)"),
                      "INSTRUCTOR " = c("LECTURER","INST([a-zA-Z]+)CTOR"),
                      "MANAGEMENT " = c("MGMT", "MGMT.","MGT(?= |\\.|,|/)"),
                      "EDUCATION " = c("EDUC(?= |,|\\.|/)"),
                      "DEPARTMENT " = c("DEPT.","DEPT"),
                      "CHAIRPERSON " = c("CHAIR ","CHAIR([a-zA-Z]+)AN"),
                      "REPRESENTATIVE " = c("REP ","REP.(?= |$)"),
                      "SALESPERSON " = c("MERCHANDISER", "SALES([a-zA-Z]+)AN"),
                      " GENERAL MANAGER " = c("G.M.(?= |$)", " GM ")
                      )