# categories are in ranked order, higher -> lower priority.
# if there is a keyword match tie score, tie-breaker goes to 
# higher priority (listed) category

industry_kw <- list ("BUSINESS" = list("BUSINESS","INVENTORY","COST","STRATEGIC","COMMERCIAL",
                                   "SALES","PROCUREMENT","PROCESS","DECISION",
                                   "MARKET","STRATEGY","ASSURANCE","ESTIMATOR","CUSTOMER",
                                   "EFFICIENCY"),
                 "FINANCE" = list("FINANCE","FINANCIAL","QUANTITATIVE","QUANT","MODELING",
                                  "CREDIT","WEALTH","BANKING","VALUATION","PORTFOLIO",
                                  "MERGER","MERGERS","ACQUISITIONS","M&A","INVESTMENT","EQUITY",
                                  "DERIVATIVES","TREASURY","PRICING","VALUE","MARKET",
                                  "ASSET","ASSETS","RISK","ACTUARY","UNDERWRITER","VENTURE",
                                  "CAPITAL","BROKER","ACTUARIAL","FUTURES"),
                 "STAFFING & RECRUITING"=list("HUMAN","TALENT","STAFFING","RECRUITING","CAPITAL",
                                              "WORKFORCE","HR"),
                 "ACCOUNTING" = list("AUDIT","AUDITOR","TAX","PAYROLL","ACCOUNTANT","FISCAL"),
                 "INSURANCE" = list("INSURANCE","CLAIMS","BROKER","AGENT"),
                 "MARKETING" = list("MARKETING","ADVERTISING","SALES","BRAND","RELATIONS",
                                    "PROMOTION","PRODUCT","DEMAND","ADVANCEMENT"),
                 "COMMUNICATIONS" = list("COMMUNICATIONS","CABLE","SATELLITE","TELEPHONE"),
                 "COMPUTER & INFORMATION TECHNOLOGY" = list("COMPUTER","INFORMATION","TECHNOLOGY",
                                                        "NETWORK","CHIP","SOFTWARE","IT","WEB"),
                 "TRANSPORTATION" = list("LOGISTICS","SUPPLY","TRANSPORTATION"),
                 "ENERGY & UTILITIES" = list("ENERGY","OIL","RENEWABLE","WASTE","RECYCLING",
                                             "ENVIRONMENT"),
                 "RETAIL/CONSUMER GOODS" = list("SALES","RETAIL","GOODS","MERCHANDISE","PRODUCTS",
                                                "WHOLESALE","APPAREL","CUSTOMER"),
                 "HOSPITAL & HEALTH CARE" = list("HOSPITAL","CARE","HEALTH"),
                 "HEALTH, WELLNESS, & FITNESS" =list("HEALTH","YOGA","FITNESS","WELLNESS","OCCUPATIONAL",
                                                     "EXERCISE","PHYSICAL"),
                 "FACILITIES" = list("MAINTENANCE","ENVIRONMENTAL","FACILITIES","FACILITY",
                                     "PROPERTY"),
                 "FOOD & BEVERAGES" = list("FOOD","BEVERAGES","WINE"),
                 "ARTS & ENTERTAINMENT" = list("ATHLETICS","RECREATIONAL","SPORTS","LEISURE",
                                     "ENTERTAINMENT","MOVIE","DANCE","MUSIC","ARTIST","ART",
                                     "CERAMICS","FINE","GALLERY","CURATOR","PHOTOGRAPHER",
                                     "WRITER","AUTHOR","SINGER","PORTFOLIO"), 
                 "REAL ESTATE" = list("REAL","ESTATE","BROKER","MORTGAGE","APPRAISAL","APPRAISER",
                                      "AGENT","PROPERTY"),
                 "HOSPITALITY/TRAVEL" = list("HOTEL","HOSPITALITY","RESERVATIONS","TRAVEL"),
                 "ENGINEERING" = list("ENGINEER","ENGINEERING"),
                 "MANUFACTURING" = list("MANUFACTURING","INDUSTRIAL","MACHINERY",
                                       "AUTOMATION"),
                 "NONPROFIT ORGANIZATION OR FUNDRAISING" = list("NGO","NONPROFIT","NON-PROFIT",
                                                                "PROFIT","GRANT","GIVING","GIFTS",
                                                                "FUNDRAISING","FUND","CHARITABLE","DONOR",
                                                                "GRANTS","GIFT","RELATIONS","FOUNDATION",
                                                                "STEWARDSHIP"),
                 "REGULATORY" = list("SAFETY","COMPLIANCE"),
                 "DATA" = list("STATISTICAL","STATISTICS","DATA")
)